In [1]:
# This is Jupyter notebook that loads the cop data
# as a pandas dataframe
#

import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

%matplotlib inline

data_folder = os.path.join(os.getcwd(), 'data')

# Step 1: Import the Data

# import the officer data
officer_file = os.path.join(data_folder, 'toy.officer_data.csv')
officer_df = pd.read_csv(officer_file)

# import the complaint data
complaint_file = os.path.join(data_folder, 'toy.complaint_data.csv')
complaint_df = pd.read_csv(complaint_file)


In [2]:
# Step 2: See the Data

# officer head
officer_df.head()

# complaint head
complaint_df.head()

crid      incident_date  beat_2012_geocoded  complaintcategory  \
0  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   
1  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   
2  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   
3  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   
4  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   

  finalfinding  officer_id  
0           EX           1  
1           EX           2  
2           EX           3  
3           EX           4  
4           EX           5

In [3]:
import chris_rasmus_graph_features

In [4]:
complaint_df_randtime = complaint_df.copy()

In [5]:
np.random.randint(1,10)

1

for index, row in complaint_df_randtime.iterrows():
    complaint_df_randtime.iloc[index]["incident_date"]  = np.random.randint(1,10)
    

In [6]:
complaint_df_randtime.shape

(13840, 6)

In [7]:
np.zeros(13840)

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [8]:
complaint_df_randtime["incident_date"] = np.zeros(13840)

In [9]:
complaint_df_randtime.head()

crid  incident_date  beat_2012_geocoded  complaintcategory finalfinding  \
0  1022797            0.0                 NaN  03G-MISCELLANEOUS           EX   
1  1022797            0.0                 NaN  03G-MISCELLANEOUS           EX   
2  1022797            0.0                 NaN  03G-MISCELLANEOUS           EX   
3  1022797            0.0                 NaN  03G-MISCELLANEOUS           EX   
4  1022797            0.0                 NaN  03G-MISCELLANEOUS           EX   

   officer_id  
0           1  
1           2  
2           3  
3           4  
4           5

In [10]:
complaint_df_randtime["incident_date"] = np.random.randint(0,6,13840)

In [11]:
complaint_df_randtime.head()

crid  incident_date  beat_2012_geocoded  complaintcategory finalfinding  \
0  1022797              2                 NaN  03G-MISCELLANEOUS           EX   
1  1022797              3                 NaN  03G-MISCELLANEOUS           EX   
2  1022797              5                 NaN  03G-MISCELLANEOUS           EX   
3  1022797              4                 NaN  03G-MISCELLANEOUS           EX   
4  1022797              1                 NaN  03G-MISCELLANEOUS           EX   

   officer_id  
0           1  
1           2  
2           3  
3           4  
4           5

In [12]:
from chris_rasmus_graph_features  import *

In [13]:
G = build_bipartite_graph(complaint_df_randtime)

In [14]:
oids = complaint_df_randtime['officer_id'].unique()

In [21]:
oid_nbrcomp = num_of_nbr_complaints(G,oids,6)

In [22]:
oid_nbrcomp[623]

array([34, 31, 29, 28, 25, 31])

In [23]:
oid_nbrcomp

{1: array([2, 4, 6, 3, 4, 3]),
 2: array([6, 6, 9, 6, 7, 6]),
 3: array([19, 19, 18, 17, 17, 17]),
 4: array([9, 8, 9, 6, 8, 8]),
 5: array([4, 6, 6, 4, 6, 5]),
 6: array([29, 25, 30, 22, 26, 22]),
 7: array([7, 6, 8, 7, 6, 4]),
 8: array([4, 4, 7, 5, 6, 3]),
 9: array([28, 28, 31, 26, 23, 32]),
 10: array([1, 2, 2, 1, 1, 1]),
 11: array([17, 16, 22, 19, 19, 19]),
 12: array([2, 1, 1, 1, 0, 1]),
 13: array([2, 1, 1, 1, 0, 1]),
 14: array([2, 1, 1, 1, 0, 1]),
 15: array([4, 2, 2, 2, 3, 2]),
 16: array([2, 2, 2, 2, 1, 2]),
 17: array([17, 17, 18, 18, 17, 16]),
 18: array([ 7, 12, 10, 10, 10,  8]),
 19: array([2, 2, 2, 2, 3, 2]),
 20: array([1, 1, 1, 1, 0, 1]),
 21: array([10,  6,  8,  9,  5,  6]),
 22: array([3, 5, 5, 4, 5, 3]),
 23: array([3, 4, 5, 2, 4, 2]),
 24: array([7, 7, 7, 5, 5, 3]),
 25: array([25, 14, 12, 19, 19, 18]),
 26: array([3, 4, 5, 2, 4, 2]),
 27: array([34, 32, 26, 41, 29, 36]),
 28: array([3, 4, 5, 2, 4, 2]),
 29: array([3, 4, 5, 2, 4, 2]),
 30: array([5, 9, 7, 5, 7, 

In [24]:
oid_dc_nbrcomp = doublecount_nbr_complaints(G, oids, 6)

In [26]:
oid_dc_nbrcomp[623]

array([ 211.,  196.,  280.,  262.,  172.,  286.])

In [29]:
oid_nbrcomp_pf = num_of_nbr_complaints_past_future(G,oids,6)

In [30]:
oid_nbrcomp_pf[623]

array([ 268.,  250.,  186.,   73.,   18.,    0.,   44.,   95.,  180.,
        262.,  255.,  400.])

In [31]:
oid_nbrcomp[623]

array([35, 32, 27, 30, 31, 26])