In [1]:
# This is Jupyter notebook that loads the cop data
# as a pandas dataframe
#

import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

%matplotlib inline

data_folder = os.path.join(os.getcwd(), 'data')

# Step 1: Import the Data

# import the officer data
officer_file = os.path.join(data_folder, 'toy.officer_data.csv')
officer_df = pd.read_csv(officer_file)

# import the complaint data
complaint_file = os.path.join(data_folder, 'toy.complaint_data.csv')
complaint_df = pd.read_csv(complaint_file)


In [2]:
complaint_df["LAG"] = np.random.randint(0,3,13840)

In [3]:
from chris_rasmus_graph_features  import *

In [4]:
G = build_bipartite_graph(complaint_df)

In [5]:
oids = complaint_df['officer_id'].unique()

In [6]:
oid_nbrcomp = num_of_nbr_complaints(G,oids,6)

In [7]:
oid_nbrcomp[1]

array([7, 3, 6, 0, 0, 0])

In [8]:
from more_graph_features  import *

In [9]:
complaint_df["complaint_type"] = np.random.randint(0,3,13840)

In [10]:
G = build_bipartite_graph_typed(complaint_df)

In [11]:
oid_nbrcomp_typed = num_of_nbr_complaints_typed(G,oids,6,include_self=False,threshold=0)

In [12]:
oid_nbrcomp_typed[0][1]

array([5, 1, 3, 0, 0, 0])

In [13]:
oid_nbrcomp_typed[1][1]

array([3, 3, 4, 0, 0, 0])

In [14]:
oid_nbrcomp_typed[2][1]

array([4, 1, 5, 0, 0, 0])

In [15]:
oid_nbrcomp_typed = num_of_nbr_complaints_typed(G,oids,6,include_self=False,threshold=1)

In [16]:
oid_nbrcomp_typed[0][1]

array([5, 1, 3, 0, 0, 0])

In [17]:
oid_nbrcomp_typed[1][1]

array([3, 3, 4, 0, 0, 0])

In [18]:
oid_nbrcomp_typed[2][1]

array([4, 1, 5, 0, 0, 0])

In [19]:
oid_nbrcomp_typed = num_of_nbr_complaints_typed(G,oids,6,include_self=False,threshold=0)

In [20]:
oid_nbrcomp_typed[0][623]

array([25, 26, 24,  0,  0,  0])

In [21]:
oid_nbrcomp_typed[1][623]

array([27, 23, 29,  0,  0,  0])

In [22]:
oid_nbrcomp_typed[2][623]

array([22, 20, 26,  0,  0,  0])

In [23]:
oid_nbrcomp_typed[0][623]+oid_nbrcomp_typed[1][623]+oid_nbrcomp_typed[2][623]

array([74, 69, 79,  0,  0,  0])

In [24]:
oid_nbrcomp_tpf = num_of_nbr_complaints_typed_past_future(G,oids,6,include_self=False,threshold=0)

In [26]:
oid_nbrcomp_tpf

{1: array([5, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0,
        0, 0, 3, 4, 0, 0, 0, 0, 1, 5, 0, 0, 0]),
 2: array([5, 2, 1, 0, 0, 0, 6, 3, 0, 0, 0, 0, 7, 1, 1, 0, 0, 0, 0, 4, 6, 0, 0,
        0, 0, 1, 6, 0, 0, 0, 0, 2, 8, 0, 0, 0]),
 3: array([18,  7,  9,  0,  0,  0, 15,  8,  7,  0,  0,  0, 16,  4,  8,  0,  0,
         0,  0, 11, 15,  0,  0,  0,  0, 15, 12,  0,  0,  0,  0,  7, 15,  0,
         0,  0]),
 4: array([9, 3, 2, 0, 0, 0, 8, 2, 1, 0, 0, 0, 6, 2, 0, 0, 0, 0, 0, 2, 8, 0, 0,
        0, 0, 3, 7, 0, 0, 0, 0, 2, 6, 0, 0, 0]),
 5: array([7, 1, 0, 0, 0, 0, 5, 3, 0, 0, 0, 0, 4, 1, 0, 0, 0, 0, 0, 1, 3, 0, 0,
        0, 0, 1, 5, 0, 0, 0, 0, 1, 6, 0, 0, 0]),
 6: array([19, 24, 12,  0,  0,  0, 21, 17, 10,  0,  0,  0, 22, 16, 12,  0,  0,
         0,  0,  3,  8,  0,  0,  0,  0,  3, 12,  0,  0,  0,  0,  2,  7,  0,
         0,  0]),
 7: array([6, 3, 5, 0, 0, 0, 5, 5, 6, 0, 0, 0, 3, 3, 6, 0, 0, 0, 0, 2, 1, 0, 0,
        0, 0, 1, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0]),
 8: array

In [ ]:
oid_nbrcomp_tpf[0][623]

In [ ]:
oid_nbrcomp_tpf[4][623]