In [1]:
# This is Jupyter notebook that loads the cop data
# as a pandas dataframe
#

import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

%matplotlib inline

data_folder = os.path.join(os.getcwd(), 'data')

# Step 1: Import the Data

# import the officer data
officer_file = os.path.join(data_folder, 'toy.officer_data.csv')
officer_df = pd.read_csv(officer_file)

# import the complaint data
complaint_file = os.path.join(data_folder, 'toy.complaint_data.csv')
complaint_df = pd.read_csv(complaint_file)


In [2]:
# Step 2: See the Data

# officer head
officer_df.head()

# complaint head
complaint_df.head()

crid      incident_date  beat_2012_geocoded  complaintcategory  \
0  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   
1  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   
2  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   
3  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   
4  1022797  01-Jan-2009  0:08                 NaN  03G-MISCELLANEOUS   

  finalfinding  officer_id  
0           EX           1  
1           EX           2  
2           EX           3  
3           EX           4  
4           EX           5

In [3]:
import chris_rasmus_graph_features

In [4]:
complaint_df_randtime = complaint_df.copy()

In [5]:
np.random.randint(1,10)

9

for index, row in complaint_df_randtime.iterrows():
    complaint_df_randtime.iloc[index]["incident_date"]  = np.random.randint(1,10)
    

In [6]:
complaint_df_randtime.shape

(13840, 6)

In [7]:
np.zeros(13840)

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [8]:
complaint_df_randtime["incident_date"] = np.zeros(13840)

In [9]:
complaint_df_randtime.head()

crid  incident_date  beat_2012_geocoded  complaintcategory finalfinding  \
0  1022797              0                 NaN  03G-MISCELLANEOUS           EX   
1  1022797              0                 NaN  03G-MISCELLANEOUS           EX   
2  1022797              0                 NaN  03G-MISCELLANEOUS           EX   
3  1022797              0                 NaN  03G-MISCELLANEOUS           EX   
4  1022797              0                 NaN  03G-MISCELLANEOUS           EX   

   officer_id  
0           1  
1           2  
2           3  
3           4  
4           5

In [10]:
complaint_df_randtime["incident_date"] = np.random.randint(0,6,13840)

In [11]:
complaint_df_randtime.head()

crid  incident_date  beat_2012_geocoded  complaintcategory finalfinding  \
0  1022797              4                 NaN  03G-MISCELLANEOUS           EX   
1  1022797              5                 NaN  03G-MISCELLANEOUS           EX   
2  1022797              2                 NaN  03G-MISCELLANEOUS           EX   
3  1022797              1                 NaN  03G-MISCELLANEOUS           EX   
4  1022797              5                 NaN  03G-MISCELLANEOUS           EX   

   officer_id  
0           1  
1           2  
2           3  
3           4  
4           5

In [12]:
from chris_rasmus_graph_features  import *

In [13]:
G = build_bipartite_graph(complaint_df_randtime)

In [14]:
oids = complaint_df_randtime['officer_id'].unique()

In [15]:
oid_nbrcomp = num_of_nbr_complaints(G,oids,6)

In [19]:
oid_nbrcomp[623]

array([31, 28, 25, 30, 28, 26])

In [17]:
oid_nbrcomp_pf = num_of_nbr_complaints_past_future(G,oids,6)

In [18]:
oid_nbrcomp_pf[623]

array([31, 27, 21, 23, 22, 18,  0,  7, 12, 17, 21, 19])

In [20]:
oid_nbrcomp[1]

array([5, 2, 4, 3, 3, 2])

In [21]:
oid_nbrcomp_pf[1]

array([5, 2, 4, 3, 3, 0, 0, 0, 0, 0, 0, 2])

In [ ]:
oid_dc_nbrcomp = doublecount_nbr_complaints(G,oids,6)

In [ ]:
oid_dc_nbrcomp[623]

In [ ]:
oid_dc_nbrcomp_pf = dounum_of_nbr_complaints_past_future(G,oids,6)