In [1]:
# This is Jupyter notebook that loads the cop data
# as a pandas dataframe
#

import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

%matplotlib inline

data_folder = os.path.join(os.getcwd(), 'data')

# Step 1: Import the Data

# import the officer data
officer_file = os.path.join(data_folder, 'toy.officer_data.csv')
officer_df = pd.read_csv(officer_file)

# import the complaint data
complaint_file = os.path.join(data_folder, 'toy.complaint_data.csv')
complaint_df = pd.read_csv(complaint_file)


In [2]:
complaint_df["LAG"] = np.random.randint(0,3,13840)

In [3]:
from chris_rasmus_graph_features  import *

In [4]:
G = build_bipartite_graph(complaint_df)

In [5]:
oids = complaint_df['officer_id'].unique()

In [6]:
oid_nbrcomp = num_of_nbr_complaints(G,oids,6)

In [7]:
oid_nbrcomp[1]

array([3, 6, 5, 0, 0, 0])

In [8]:
from more_graph_features  import *

In [9]:
complaint_df["complaint_type"] = np.random.randint(0,3,13840)

In [10]:
G = build_bipartite_graph_typed(complaint_df)

In [11]:
oid_nbrcomp_typed = num_of_nbr_complaints_typed(G,oids,6,include_self=False,threshold=0)

In [12]:
oid_nbrcomp_typed[0][1]

array([3, 3, 1, 0, 0, 0])

In [13]:
oid_nbrcomp_typed[1][1]

array([3, 3, 5, 0, 0, 0])

In [15]:
oid_nbrcomp_typed[2][1]

array([3, 4, 2, 0, 0, 0])

In [16]:
oid_nbrcomp_typed = num_of_nbr_complaints_typed(G,oids,6,include_self=False,threshold=1)

In [17]:
oid_nbrcomp_typed[0][1]

array([0, 0, 0, 0, 0, 0])

In [18]:
oid_nbrcomp_typed[1][1]

array([0, 0, 0, 0, 0, 0])

In [19]:
oid_nbrcomp_typed[2][1]

array([0, 0, 0, 0, 0, 0])

In [20]:
oid_nbrcomp_typed = num_of_nbr_complaints_typed(G,oids,6,include_self=False,threshold=0)

In [21]:
oid_nbrcomp_typed[0][623]

array([23, 25, 25,  0,  0,  0])

In [22]:
oid_nbrcomp_typed[1][623]

array([29, 26, 21,  0,  0,  0])

In [23]:
oid_nbrcomp_typed[2][623]

array([27, 24, 24,  0,  0,  0])

In [24]:
oid_nbrcomp_typed[0][623]+oid_nbrcomp_typed[1][623]+oid_nbrcomp_typed[2][623]

array([79, 75, 70,  0,  0,  0])