In [2]:
# The last line is just for Jupyter.  It tells matplotlib where to plot.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib notebook   

# We will use gradient descent to solve linear least squares
Minimizing
$$ \| Ax - b \|_{2}^{2}, $$
and showing off the use of LaTex inside Markdown.


In [3]:
A = np.random.randn(6,3)
A

array([[ 1.15060602, -0.01218118, -0.04796248],
       [ 1.15437098, -0.39000259,  2.12394918],
       [-0.5050806 ,  0.595549  , -0.28412123],
       [-1.26502479, -0.02941371, -0.9850352 ],
       [ 0.46446842,  0.9712223 ,  2.88669233],
       [-0.99269205,  0.34621931, -3.24982113]])

In [4]:
b = np.random.randn(6,1)
b

array([[-0.22250668],
       [-0.32637213],
       [-0.09209012],
       [ 1.67930288],
       [-1.31278255],
       [ 0.17752924]])

In [5]:
x = np.zeros((3,1))
x

array([[ 0.],
       [ 0.],
       [ 0.]])

In [6]:
# This will produce an error.
# * does not multiply matrices
A*x

ValueError: operands could not be broadcast together with shapes (6,3) (3,1) 

In [7]:
# A.dot(x) is the result of multiplying A by the vector x
A.dot(x)

array([[ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 0.]])

In [8]:
# It also works for matrices
M1 = np.array([[1, 1],[0, 1]])
print "M1: \n", M1
M2 = np.array([[1, 0],[0, 2]])
print "M2: \n" , M2
print "M1*M2: \n", M1.dot(M2)

M1: 
[[1 1]
 [0 1]]
M2: 
[[1 0]
 [0 2]]
M1*M2: 
[[1 2]
 [0 2]]


In [9]:
Atrans = A.transpose()
Atrans
    

array([[ 1.15060602,  1.15437098, -0.5050806 , -1.26502479,  0.46446842,
        -0.99269205],
       [-0.01218118, -0.39000259,  0.595549  , -0.02941371,  0.9712223 ,
         0.34621931],
       [-0.04796248,  2.12394918, -0.28412123, -0.9850352 ,  2.88669233,
        -3.24982113]])

In [10]:
# we now define the function we want to minimize
def f(x):
    return sum((A.dot(x) - b)**2)
f(x)

array([ 4.73948141])

Recall that the gradient is
$$ 2 A^T (Ax - b) $$

In [11]:
# this is a funtion that returns its gradient
def grad_f(x):
    return 2*Atrans.dot(A.dot(x)-b)

grad_f(x)

array([[  6.99319359],
       [  2.37556394],
       [ 13.3541423 ]])

In [12]:
r = np.random.randn(3,1)*1e-6
r

array([[  2.03599178e-08],
       [  5.45307095e-07],
       [ -8.73490800e-08]])

In [13]:
f(x+r) - f(x)

array([  2.71321219e-07])

In [14]:
# to multiply g by r, we could first turn it into a row vector by taking its transpose
grad_f(x).transpose().dot(r)

array([[  2.71320673e-07]])

In [15]:
# or, we could turn them into one-dimensional arrays by slicing
grad_f(x)[:,0].dot(r[:,0])

2.7132067308217276e-07

In [16]:
r[:,0]

array([  2.03599178e-08,   5.45307095e-07,  -8.73490800e-08])

In [18]:
r[:,0].shape

(3,)

In [19]:
r.shape

(3, 1)

In [23]:
# play with this line to see more examples
r = np.random.randn(3,1)*1e-3
[f(x+r) - f(x), np.dot(grad_f(x)[:,0],r[:,0])]

[array([ 0.00880828]), 0.0087974122017961051]

In [24]:
def grad_descent(x0, f, g, tol=10**(-6)):

    f0 = f(x0)  # initial value
    g0 = g(x0)  # initial gradient
    
    step_size = 0.1  # initially
    
    while ((np.linalg.norm(g0) > tol) & (step_size > tol)):
        
        xnew = x0-step_size*g0
        fnew = f(xnew)

        if (fnew < f0):
            f0 = fnew   # the best function value
            x0 = xnew   # the corresponding vector
            g0 = g(x0)  # and, its gradient
            print f0    # this will be a pain in a long run
        else:
            step_size = step_size/2
            
    return x0

In [25]:
x1 = grad_descent(np.zeros((3,1)), f, grad_f)

[ 2.81413791]
[ 2.39362162]
[ 2.20839309]
[ 2.07103017]
[ 1.95259173]
[ 1.84750624]
[ 1.75378369]
[ 1.6700981]
[ 1.59534154]
[ 1.5285429]
[ 1.46884254]
[ 1.41547726]
[ 1.36776837]
[ 1.32511171]
[ 1.28696891]
[ 1.2528599]
[ 1.22235635]
[ 1.19507588]
[ 1.17067703]
[ 1.14885476]
[ 1.1293365]
[ 1.11187864]
[ 1.09626345]
[ 1.08229625]
[ 1.06980298]
[ 1.05862802]
[ 1.04863218]
[ 1.03969101]
[ 1.03169319]
[ 1.02453916]
[ 1.01813989]
[ 1.01241573]
[ 1.00729545]
[ 1.00271534]
[ 0.99861841]
[ 0.99495367]
[ 0.99167554]
[ 0.98874323]
[ 0.98612025]
[ 0.98377398]
[ 0.98167522]
[ 0.97979785]
[ 0.97811854]
[ 0.97661637]
[ 0.97527267]
[ 0.97407072]
[ 0.97299556]
[ 0.97203382]
[ 0.97117353]
[ 0.970404]
[ 0.96971564]
[ 0.9690999]
[ 0.96854911]
[ 0.96805643]
[ 0.96761572]
[ 0.9672215]
[ 0.96686887]
[ 0.96655343]
[ 0.96627127]
[ 0.96601888]
[ 0.96579311]
[ 0.96559116]
[ 0.96541051]
[ 0.96524891]
[ 0.96510437]
[ 0.96497507]
[ 0.96485941]
[ 0.96475596]
[ 0.96466341]
[ 0.96458063]
[ 0.96450658]
[ 0.96444035]


In [26]:
# the best vector
x1

array([[-0.74353994],
       [-1.05497996],
       [ 0.01158344]])

In [27]:
# the fuction value there
f(x1)

array([ 0.96387868])

In [28]:
# the gradient at x1
grad_f(x1)

array([[  4.57893717e-07],
       [  8.60847059e-07],
       [ -1.89797915e-07]])

In [29]:
# the norm of the gradient
np.linalg.norm(grad_f(x1))

9.9335168155578283e-07

## in larger dimensions

We now make a new problem.  A and b were global variables and f and grad_f know about them.
So, we do not need to redefine f and grad_f.  But, we do need to redefine Atrans, which is used inside f.

In [30]:
np.random.seed(1)
n = 10
A = np.random.randn(n,n)
Atrans = A.transpose()
b = np.zeros((n,1))

x0 = np.random.randn(n,1)
f(x0)

array([ 40.34491096])

In [31]:
x1 = grad_descent(x0,f,grad_f,tol=10**(-3))

[ 32.58916415]
[ 2.56896543]
[ 1.49271742]
[ 1.22090968]
[ 1.02169664]
[ 0.86228249]
[ 0.73319711]
[ 0.62808727]
[ 0.54216454]
[ 0.47169504]
[ 0.41371931]
[ 0.36587093]
[ 0.32624811]
[ 0.29331768]
[ 0.26584105]
[ 0.24281607]
[ 0.22343082]
[ 0.20702679]
[ 0.19306928]
[ 0.18112365]
[ 0.1708362]
[ 0.16191877]
[ 0.15413631]
[ 0.14729683]
[ 0.14124331]
[ 0.13584712]
[ 0.13100274]
[ 0.12662343]
[ 0.12263779]
[ 0.11898689]
[ 0.11562201]
[ 0.11250279]
[ 0.10959565]
[ 0.10687264]
[ 0.10431041]
[ 0.10188936]
[ 0.09959303]
[ 0.09740751]
[ 0.09532102]
[ 0.09332354]
[ 0.09140651]
[ 0.08956261]
[ 0.08778549]
[ 0.0860697]
[ 0.08441048]
[ 0.08280367]
[ 0.08124565]
[ 0.07973318]
[ 0.07826344]
[ 0.0768339]
[ 0.07544228]
[ 0.07408657]
[ 0.07276494]
[ 0.07147574]
[ 0.07021746]
[ 0.06898872]
[ 0.06778829]
[ 0.06661499]
[ 0.06546778]
[ 0.06434566]
[ 0.06324773]
[ 0.06217314]
[ 0.06112109]
[ 0.06009085]
[ 0.05908171]
[ 0.05809304]
[ 0.0571242]
[ 0.05617464]
[ 0.05524378]
[ 0.05433111]
[ 0.05343615]
[ 0.05255

In [32]:
f(x1)

array([  2.22580105e-06])

That took a lot of iterations, and it was only 10 dimensional!
So, we will limit the number of iterations of gradient descent,
and stop all the printing.

In [33]:
def grad_descent(x0, f, g, tol=10**(-6), max_iters = 10**5):

    f0 = f(x0)
    g0 = g(x0)
    
    step_size = 0.1
    iters = 0
    
    while ((np.linalg.norm(g0) > tol) & (step_size > tol) & (iters < max_iters)):
        xnew = x0-step_size*g0
        fnew = f(xnew)
        iters += 1
        
        if (fnew < f0):
            f0 = fnew
            x0 = xnew
            g0 = g(x0)
        else:
            step_size = step_size/2
    
    print "function value:", f0
    print "number iterations:", iters
    
    return x0


With this protection in place, we can handle larger matrices

In [34]:
np.random.seed(1)
n = 100
A = np.random.randn(n,n)
Atrans = A.transpose()
b = np.zeros((n,1))

x0 = np.random.randn(n,1)
f(x0)

array([ 9992.15931358])

In [35]:
x1 = grad_descent(x0,f,grad_f,tol=10**(-3),max_iters=10)

function value: [ 194.18072624]
number iterations: 10


In [36]:
x1 = grad_descent(x0,f,grad_f,tol=10**(-3),max_iters=100)
x1 = grad_descent(x0,f,grad_f,tol=10**(-3),max_iters=1000)
x1 = grad_descent(x0,f,grad_f,tol=10**(-3),max_iters=10000)
x1 = grad_descent(x0,f,grad_f,tol=10**(-3),max_iters=100000)

function value: [ 4.4088504]
number iterations: 100
function value: [ 0.12314598]
number iterations: 1000
function value: [ 0.00682233]
number iterations: 10000
function value: [  5.84378556e-05]
number iterations: 100000


To see how long that took, we can time it.

In [37]:
%time x1 = grad_descent(x0,f,grad_f,tol=10**(-3),max_iters=10000)

function value: [ 0.00682233]
number iterations: 10000
CPU times: user 2.25 s, sys: 36.2 ms, total: 2.28 s
Wall time: 1.21 s


## Computing it directly using matrix inversion
We use the following formula from lecture 2:
$$ x  = (A^{T} A)^{-1} A^{T} b $$


In [38]:
x = np.linalg.inv(Atrans.dot(A)).dot(Atrans.dot(b))
f(x)

array([ 0.])

# Things to be careful of when using vectors
Some of these lines might surprise you until you understand what's going on.

In [3]:
x = np.zeros((3,1))

In [4]:
y = x
y[0] = 1
x

array([[ 1.],
       [ 0.],
       [ 0.]])

In [5]:
y -= np.random.randn(3,1)
y

array([[ 2.13917673],
       [ 0.43729632],
       [ 0.33470413]])

In [6]:
x

array([[ 2.13917673],
       [ 0.43729632],
       [ 0.33470413]])

In [7]:
y = y + 4
y

array([[ 6.13917673],
       [ 4.43729632],
       [ 4.33470413]])

In [8]:
x

array([[ 2.13917673],
       [ 0.43729632],
       [ 0.33470413]])